# //////////////////////////////////////////////////////////////////////////////
#                                  SERVICES
# //////////////////////////////////////////////////////////////////////////////

services:

 # ============== SPA SERVER ==============

  spa-server:
    container_name: spa-server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./data/certs:/gateway/certs
      - ../fwknop-totp:/gateway/fwknop
    cap_add:
      - NET_ADMIN
    networks:
      - spa-net

  # ============== SPA CLIENT ==============

  spa-client:
    container_name: spa-client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ../fwknop-totp:/client/fwknop
    networks:
      - spa-net
    depends_on:
      - spa-server

# //////////////////////////////////////////////////////////////////////////////
#                                  NETWORKS
# //////////////////////////////////////////////////////////////////////////////

networks:
  spa-net: {}
